// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abpynthibmcuyxzkjcvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicHludGhpYm1jdXl4emtqY3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjgxMTgsImV4cCI6MjA1ODcwNDExOH0.WRQLBksvxLoLhEScPCacIUVM5oKpXozWeiUNAhSW_DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);